Repository sinatra/sinatra, pull requests merged in 2020-03, with the labels that each got.

#1341 Ruby 2: use __dir__ instead of File.dirname(__FILE__)
  README.de.md
  README.es.md
  README.fr.md
  README.hu.md
  README.ja.md
  README.ko.md
  README.md
  README.pt-br.md
  README.pt-pt.md
  README.ru.md
  README.zh.md
  lib/sinatra/base.rb
  test/asciidoctor_test.rb
  test/builder_test.rb
  test/coffee_test.rb
  test/creole_test.rb
  test/encoding_test.rb
  test/erb_test.rb
  test/filter_test.rb
  test/haml_test.rb
  test/helper.rb
  test/helpers_test.rb
  test/less_test.rb
  test/liquid_test.rb
  test/markaby_test.rb
  test/markdown_test.rb
  test/mediawiki_test.rb
  test/nokogiri_test.rb
  test/rabl_test.rb
  test/radius_test.rb
  test/rdoc_test.rb
  test/sass_test.rb
  test/scss_test.rb
  test/settings_test.rb
  test/slim_test.rb
  test/static_test.rb
  test/stylus_test.rb
  test/templates_test.rb
  test/textile_test.rb
  test/wlang_test.rb
  test/yajl_test.rb
Labels: Wishlist

#1250 add QuietLogger that excludes pathes from Rack::CommonLogger
  sinatra-contrib/README.md
  sinatra-contrib/lib/sinatra/quiet_logger.rb
  sinatra-contrib/spec/quiet_logger_spec.rb
Labels: feature, sinatra-contrib

#1214 Use prepend instead of include for helpers. Fixes #1213
  lib/sinatra/base.rb
  sinatra-contrib/lib/sinatra/namespace.rb
  test/helpers_test.rb
Labels: feedback

#1255 sinatra-namespace: Allow for `set :<engine>`
  sinatra-contrib/lib/sinatra/namespace.rb
  sinatra-contrib/spec/namespace_spec.rb
Labels: feature

#1239 Add default_content_type setting. Fixes #1238
  README.md
  lib/sinatra/base.rb
  test/response_test.rb
  test/settings_test.rb
Labels: feature, feedback
